typography_spectrum: 0.91911587577931
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.507756010813657
  lightness: 0.1917217447759934
  saturation: 0.7537402832848342
  rhythmicContrast: 0.12605183025582298
github: true
layout_spectrum: 0.17839197623663317
author:
  name: Alexandre Amaral
  email: alexandreamaral.click@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bd705930-d54e-481c-8876-1c908c83cd38.png
name: alexandreamaral
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: portfolio
    id: 8bdc2aa3-fe6c-4b13-a291-8e3e17e6d09c
    type: content
  - name: Quem sou
    id: 686349e0-baf9-400b-8d2c-48d52e486696
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f88d4dc0-25a5-4b8b-b87b-c558e7989916.png
title: alexandreamaral
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5bb75fd5-fd06-457c-abcb-153fc31e1c47.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5bb75fd5-fd06-457c-abcb-153fc31e1c47.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e3b88e9-518b-466f-b8d0-0d96ea488870.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e3b88e9-518b-466f-b8d0-0d96ea488870.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: photography and software education
purpose:
  - type: contact
    url: 'mailto:alexandreamaral.click@gmail.com'
    label: Contact me
