layout_spectrum: 0.17839197623663317
typography_spectrum: 0.91911587577931
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.507756010813657
  lightness: 0.1917217447759934
  saturation: 0.7537402832848342
  rhythmicContrast: 0.12605183025582298
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: alexandreamaral
content: []
title: alexandreamaral
description: photography and software education
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f88d4dc0-25a5-4b8b-b87b-c558e7989916.png
author:
  name: Alexandre Amaral
  email: alexandreamaral.click@gmail.com
